import os
from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.document_loaders import CSVLoader
#use dotenv to load environmnet variables from a .env file but now we are using local huggingface models 
# so we don't need to use the OPENAI_API_KEY anymore but we will keep it for future use
from dotenv import load_dotenv

load_dotenv()


# Loading document from the docs folder
# This is the first step of the ingestion pipeline
def load_documents(docs_path="docs"):  # Giving default value to docs_path
    print(f"loading documents from {docs_path}")

    if not os.path.exists(docs_path):  # If the docs_path does not exist, raise an error
        raise FileNotFoundError(f"Directory {docs_path} does not exist.")

    # Loading documents from the docs folder using DirectoryLoader
    loader = DirectoryLoader(
        docs_path,
        glob="*.txt",  # Glob pattern to match all text files in the directory
        loader_cls=TextLoader,  # Loader class to use for loading the documents
        loader_kwargs={"encoding": "utf-8"},  # Forces Python to read files in UTF-8
    )

    documents = loader.load()

    if len(documents) == 0:
        raise FileNotFoundError(
            f"No documents found in {docs_path}. Please add some text files to the directory."
        )

    for i, doc in enumerate(documents[:50]):
        print(f"Document {i+1}: {doc.metadata['source']}")  # Printing the source
        print(f"Content: {doc.page_content[:100]}...")  # Printing the first 100 chars
        print(f"Length: {len(doc.page_content)} characters\n")

    return documents 


def split_documents(documents, chunk_size=2000, chunk_overlap=50):
    """
    Function to split large documents into smaller text segments (chunks).
    - documents: The list of raw Document objects loaded from your docs folder.
    - chunk_size: The target number of characters each text chunk should contain.
    - chunk_overlap: The number of characters to repeat between consecutive chunks.
    """
    # Print status message to the terminal so we know the splitting phase has started
    print("splitting documents into the chunks")

    # Initialize LangChain's character-based text splitter configuration
    text_splitter = CharacterTextSplitter(
        chunk_size=chunk_size,  # Set the maximum target character length for each chunk
        chunk_overlap=chunk_overlap,  # Set how many characters overlap between adjacent chunks
        separator="\n",  # Tell the splitter to break text at single newlines rather than paragraphs
    )

    # Execute the splitting logic on our list of long input documents
    # This outputs a flat list containing all the newly generated smaller chunk Document objects
    all_chunks = text_splitter.split_documents(documents)

    # Check if the text splitter successfully generated any chunks
    if all_chunks:
        # Loop through only the first 5 chunks to display a preview in the terminal
        # 'i' tracks the index loop number, 'chunk' holds the individual Document object
        for i, chunk in enumerate(all_chunks[:5]):
            # Print a clean header showing the current chunk number (1-indexed for humans)
            print(f"\n--Chunk {i+1}--")

            # Extract and print the metadata 'source' (the file name/path where this chunk came from)
            print(f"source: {chunk.metadata['source']}")

            # Calculate and print the actual character count of this specific text chunk
            print(f"length: {len(chunk.page_content)} characters")

            # Print the actual text snippet contained inside this specific chunk
            print(f"content: {chunk.page_content}")

            # Print a visual divider line of 50 hyphens to separate chunks visually in logs
            print("-" * 50)

        # After the loop finishes, check if there are more than 5 total chunks in our database list
        if len(all_chunks) > 5:
            # Print a summary statement calculating how many remaining chunks were not previewed
            print(f"\n-- and {len(all_chunks) - 5} more chunks\n")

    return all_chunks

def create_vector_store(chunks,persist_directory="db/chroma_db"):#passing the chunks to the function and asking for a persist directory to store the vector store
    """create and persist chromaDB vector store """
    print("creating embedding and storing in ChromaDB...")

#using the HuggingFaceEmbeddings class to create an embedding model using the "sentence-transformers/all-MiniLM-L6-v2" model. 
# This model is a smaller version of the MiniLM model, which is designed for efficient and effective sentence embeddings. 
# The embeddings generated by this model will be used to represent the text chunks in a vector space, allowing for similarity searches and other operations in the ChromaDB vector store.
    embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

    #create chromaDB vector store 
    print("---creating vector store---")
    #using function from langchain_chroma to create a vector store from the chunks we created in the previous step.
    vector_store=Chroma.from_documents(
        documents=chunks,#passing chunks that we created in the previous step
        embedding=embedding_model,  #telling which embedding model to use for creating the vector store
        persist_directory=persist_directory,#specifying the directory to persist the vector store
        collection_metadata={"hnsw:space": "cosine"}#we will discuss this later
    )
    
    print("---finished creating vector store")

    print(f"vector store created and save to {persist_directory}")

    return vector_store


def main():
    print("--- starting main function ---")
    documents = load_documents(docs_path="docs")
    print(f"Successfully loaded {len(documents)} total document(s).")
    
    chunks=split_documents(documents)

    vector_store=create_vector_store(chunks)


if __name__ == "__main__":
    main()




#                 ESSENTIAL COMMANDS FOR SETTING UP THE INGESTION PIPELINE ENVIRONMENT
# ==================================================================================
# Run these commands inside your terminal with your virtual environment active (venv)
#
# 1. Install Python Dotenv (To read configuration variables, though currently using local models)
#    pip install python-dotenv
#
# 2. Install LangChain Core Framework & Community Utilities
#    pip install langchain
#
# 3. Clean up any broken/conflicting older packages before installing database tools
#    pip uninstall langchain-chroma chromadb -y
#
# 4. Install ChromaDB and LangChain-Chroma Integration (Using pre-compiled binaries for Windows)
#    pip install chromadb langchain-chroma --prefer-binary
#
# 5. Install LangChain HuggingFace Extension Wrapper
#    pip install langchain-huggingface
#
# 6. Install Sentence-Transformers Engine (Bypassing network crashes and ignoring corrupt cache data)
#    pip install sentence-transformers --no-cache-dir --default-timeout=1000
#
# OS LEVEL PREREQUISITE (For Windows C++ DLL errors):
#    If Windows crashes with an 'ImportError' regarding 'chromadb_rust_bindings',
#    download and install the Microsoft Visual C++ Redistributable package, then restart your PC:
#     URL: https://aka.ms/vs/17/release/vc_redist.x64.exe
